version: '3'
services:
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: sister
      POSTGRES_PASSWORD: pass_SISTER212
    volumes:
      - ./moodlecloud.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:5.0.5-alpine
  moodlecloud:
    image: sudarko/moodlecloud:0.1 
    ports:
      - "8088:80"
