version: '3'
services:
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: pass_CLOUD
    volumes:
      - ./moodlecloud.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:5.0.5-alpine
  moodlecloud:
    image: sudarko/moodlecloud:0.1 
    volumes:
      - ./config.php:/var/www/html/config.php
    ports:
      - "8088:80"
